# Generated by Django 3.0.3 on 2020-09-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblbankinfo',
            fields=[
                ('bankinfo_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('acct_num', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tblinvestment',
            fields=[
                ('investment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblLog',
            fields=[
                ('log_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('lg_user_name', models.CharField(max_length=100)),
                ('lg_action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tblpartners',
            fields=[
                ('partner_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('address_site', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=100)),
                ('address_zip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tblproperty',
            fields=[
                ('property_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('add_site', models.CharField(max_length=100)),
                ('add_city', models.CharField(max_length=100)),
                ('add_state', models.CharField(max_length=100)),
                ('add_zip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tblusers',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_status', models.CharField(max_length=100)),
            ],
        ),
    ]
