# Generated by Django 3.0.3 on 2020-09-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vwp_app', '0002_auto_20200921_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tblpartners',
            new_name='Tblpartner',
        ),
        migrations.RenameModel(
            old_name='Tblusers',
            new_name='Tbluser',
        ),
    ]
